### ISSUE TITLE
Fatal error: Uncaught exception  'GoogleUrl\Exception\CaptachaException' 

### ISSUE THREAD

**Issue by 2ethylamid** [SneakyBobito/google-url#13]
Fatal error: Uncaught exception 'GoogleUrl\Exception\CaptachaException' with message 'API Error: ' in /var/www/bgmt/data/www/bgmtsystems.ru/services/parcer/lib/GoogleUrl.php:371 Stack trace: #0 /var/www/bgmt/data/www/bgmtsystems.ru/services/parcer/index.php(22): GoogleUrl->search('simpsons') #1 {main} thrown in /var/www/bgmt/data/www/bgmtsystems.ru/services/parcer/lib/GoogleUrl.php on line 371

**Comment by SneakyBobito** [comment]
This is because you have submitted a lot of queries to google, or because you use a proxy that has already abused of google. Google needs a captcha to continue. 

You have to handle this error with a try catch block : 

```php
try{
 // ....
$googleUrl->search('simpsons');
 // ....
}catch( GoogleUrl\Exception\CaptachaException $e){

  // because you are temporary blacklisted with google
  // just wait or if you use a proxy remove temporary this proxy from the list

}


PS : A captcha solving interterface is planned for the v2 allowing you to implement your own way to solve captcha.

PPS : I just noticed the typo on captacha instead of captcha, will be fixed with v2 too

Thanks for your interest in the library
